// -*- coding: utf-8 -*-
// Configuración compartida entre herramientas

export const BOOK_MAP = {
  // NT
  'mateo': { kjv2003: 'Matthew', display: 'Mateo', strongType: 'G' },
  'marcos': { kjv2003: 'Mark', display: 'Marcos', strongType: 'G' },
  'lucas': { kjv2003: 'Luke', display: 'Lucas', strongType: 'G' },
  'juan': { kjv2003: 'John', display: 'Juan', strongType: 'G' },
  'hechos': { kjv2003: 'Acts', display: 'Hechos', strongType: 'G' },
  'romanos': { kjv2003: 'Romans', display: 'Romanos', strongType: 'G' },
  'corintios1': { kjv2003: 'I_Corinthians', display: '1 Corintios', strongType: 'G' },
  'corintios2': { kjv2003: 'II_Corinthians', display: '2 Corintios', strongType: 'G' },
  'galatas': { kjv2003: 'Galatians', display: 'Gálatas', strongType: 'G' },
  'efesios': { kjv2003: 'Ephesians', display: 'Efesios', strongType: 'G' },
  'filipenses': { kjv2003: 'Philippians', display: 'Filipenses', strongType: 'G' },
  'colosenses': { kjv2003: 'Colossians', display: 'Colosenses', strongType: 'G' },
  'tesalonicenses1': { kjv2003: 'I_Thessalonians', display: '1 Tesalonicenses', strongType: 'G' },
  'tesalonicenses2': { kjv2003: 'II_Thessalonians', display: '2 Tesalonicenses', strongType: 'G' },
  'timoteo1': { kjv2003: 'I_Timothy', display: '1 Timoteo', strongType: 'G' },
  'timoteo2': { kjv2003: 'II_Timothy', display: '2 Timoteo', strongType: 'G' },
  'tito': { kjv2003: 'Titus', display: 'Tito', strongType: 'G' },
  'filemon': { kjv2003: 'Philemon', display: 'Filemón', strongType: 'G' },
  'hebreos': { kjv2003: 'Hebrews', display: 'Hebreos', strongType: 'G' },
  'santiago': { kjv2003: 'James', display: 'Santiago', strongType: 'G' },
  'pedro1': { kjv2003: 'I_Peter', display: '1 Pedro', strongType: 'G' },
  'pedro2': { kjv2003: 'II_Peter', display: '2 Pedro', strongType: 'G' },
  'juan1': { kjv2003: 'I_John', display: '1 Juan', strongType: 'G' },
  'juan2': { kjv2003: 'II_John', display: '2 Juan', strongType: 'G' },
  'juan3': { kjv2003: 'III_John', display: '3 Juan', strongType: 'G' },
  'judas': { kjv2003: 'Jude', display: 'Judas', strongType: 'G' },
  'apocalipsis': { kjv2003: 'Revelation', display: 'Apocalipsis', strongType: 'G' },
  // AT
  'genesis': { wlc: 'Gen', display: 'Génesis', strongType: 'H' },
  'exodus': { wlc: 'Exod', display: 'Éxodo', strongType: 'H' },
  'leviticus': { wlc: 'Lev', display: 'Levítico', strongType: 'H' },
  'numbers': { wlc: 'Num', display: 'Números', strongType: 'H' },
  'deuteronomy': { wlc: 'Deut', display: 'Deuteronomio', strongType: 'H' },
  'joshua': { wlc: 'Josh', display: 'Josué', strongType: 'H' },
  'judges': { wlc: 'Judg', display: 'Jueces', strongType: 'H' },
  'ruth': { wlc: 'Ruth', display: 'Rut', strongType: 'H' },
  '1samuel': { wlc: '1Sam', display: '1 Samuel', strongType: 'H' },
  '2samuel': { wlc: '2Sam', display: '2 Samuel', strongType: 'H' },
  '1kings': { wlc: '1Kgs', display: '1 Reyes', strongType: 'H' },
  '2kings': { wlc: '2Kgs', display: '2 Reyes', strongType: 'H' },
  '1chronicles': { wlc: '1Chr', display: '1 Crónicas', strongType: 'H' },
  '2chronicles': { wlc: '2Chr', display: '2 Crónicas', strongType: 'H' },
  'ezra': { wlc: 'Ezra', display: 'Esdras', strongType: 'H' },
  'nehemiah': { wlc: 'Neh', display: 'Nehemías', strongType: 'H' },
  'esther': { wlc: 'Esth', display: 'Ester', strongType: 'H' },
  'job': { wlc: 'Job', display: 'Job', strongType: 'H' },
  'psalms': { wlc: 'Ps', display: 'Salmos', strongType: 'H' },
  'proverbs': { wlc: 'Prov', display: 'Proverbios', strongType: 'H' },
  'ecclesiastes': { wlc: 'Eccl', display: 'Eclesiastés', strongType: 'H' },
  'songofsongs': { wlc: 'Song', display: 'Cantares', strongType: 'H' },
  'isaiah': { wlc: 'Isa', display: 'Isaías', strongType: 'H' },
  'jeremiah': { wlc: 'Jer', display: 'Jeremías', strongType: 'H' },
  'lamentations': { wlc: 'Lam', display: 'Lamentaciones', strongType: 'H' },
  'ezekiel': { wlc: 'Ezek', display: 'Ezequiel', strongType: 'H' },
  'daniel': { wlc: 'Dan', display: 'Daniel', strongType: 'H' },
  'hosea': { wlc: 'Hos', display: 'Oseas', strongType: 'H' },
  'joel': { wlc: 'Joel', display: 'Joel', strongType: 'H' },
  'amos': { wlc: 'Amos', display: 'Amós', strongType: 'H' },
  'obadiah': { wlc: 'Obad', display: 'Abdías', strongType: 'H' },
  'jonah': { wlc: 'Jonah', display: 'Jonás', strongType: 'H' },
  'micah': { wlc: 'Mic', display: 'Miqueas', strongType: 'H' },
  'nahum': { wlc: 'Nah', display: 'Nahum', strongType: 'H' },
  'habakkuk': { wlc: 'Hab', display: 'Habacuc', strongType: 'H' },
  'zephaniah': { wlc: 'Zeph', display: 'Sofonías', strongType: 'H' },
  'haggai': { wlc: 'Hag', display: 'Hageo', strongType: 'H' },
  'zechariah': { wlc: 'Zech', display: 'Zacarías', strongType: 'H' },
  'malachi': { wlc: 'Mal', display: 'Malaquías', strongType: 'H' }
}

export const KJV2003_PATH_TEMPLATE = "ref/sword_kjv/capitulos2003/{book_kjv2003}-{chapter_padded}.osis.xml"

export const WLC_PATH_TEMPLATE = "ref/openscriptures_morphhb/wlc/{wlc_code}.xml"
