#!/bin/sh
for i in Acts Hebrews II_Corinthians I_Corinthians John Luke Mark Matthew Revelation Romans; do 
  echo $i
  for j in $i*; do
    n=`echo $j | sed -e "s/-08/-07/g" |\
      sed -e "s/-09/-08/g" |\
      sed -e "s/-10/-09/g" |\
      sed -e "s/-11/-10/g" |\
      sed -e "s/-12/-11/g" |\
      sed -e "s/-13/-12/g" |\
      sed -e "s/-14/-13/g" |\
      sed -e "s/-15/-14/g" |\
      sed -e "s/-16/-15/g" |\
      sed -e "s/-17/-16/g" |\
      sed -e "s/-18/-17/g" |\
      sed -e "s/-19/-18/g" |\
      sed -e "s/-20/-19/g" |\
      sed -e "s/-21/-20/g" |\
      sed -e "s/-22/-21/g" |\
      sed -e "s/-23/-22/g" |\
      sed -e "s/-24/-23/g" |\
      sed -e "s/-25/-24/g" |\
      sed -e "s/-26/-25/g" |\
      sed -e "s/-27/-26/g" |\
      sed -e "s/-28/-27/g" |\
      sed -e "s/-29/-28/g"
    `
    echo "$j -> $n"
    mv $j $n
  done; 
  read

done

